# 3. Operaciones básicas
> Por Arturo Erdely

## 3.1 Aritmética

In [73]:
2 + 3, 2 - 3, 2*3, 2/3, 2^3

(5, -1, 6, 0.6666666666666666, 8)

In [74]:
2/3, 2\3

(0.6666666666666666, 1.5)

In [75]:
2//7 + 3//8, 2//7 * 3//8, (2//7)^(3//8)

(37//56, 3//28, 0.6251359623239413)

In [76]:
√4, √2 

(2.0, 1.4142135623730951)

In [77]:
π 

π = 3.1415926535897...

In [78]:
typeof(π)

Irrational{:π}

In [79]:
2 + π 

5.141592653589793

In [80]:
2 + big(π)

5.141592653589793238462643383279502884197169399375105820974944592307816406286198

**División entera y residuo**

In [81]:
div(9, 4)

2

In [82]:
rem(9, 4)

1

In [83]:
divrem(9, 4)

(2, 1)

O bien mediante `\div` $\div$ y `%`

In [84]:
9 ÷ 4, 9/4 

(2, 2.25)

In [85]:
9 % 4

1

## 3.2 Vectores

In [86]:
x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [87]:
x + 1 # error

LoadError: MethodError: no method matching +(::Array{Int64,1}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(!Matched::Missing, ::Number) at missing.jl:115
  +(!Matched::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:116
  ...

In [88]:
x .+ 1 # se agrega el punto antes del operador para vectorizarlo

3-element Array{Int64,1}:
 2
 3
 4

In [89]:
x .^ 2

3-element Array{Int64,1}:
 1
 4
 9

In [90]:
y = [10, 100, 1_000]

3-element Array{Int64,1}:
   10
  100
 1000

In [95]:
x + y

3-element Array{Int64,1}:
   11
  102
 1003

In [92]:
x * y # error

LoadError: MethodError: no method matching *(::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  *(!Matched::LinearAlgebra.Adjoint{var"#s826",var"#s8261"} where var"#s8261"<:(AbstractArray{T,1} where T) where var"#s826"<:Number, ::AbstractArray{var"#s825",1} where var"#s825"<:Number) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\adjtrans.jl:283
  *(!Matched::LinearAlgebra.Transpose{T,var"#s826"} where var"#s826"<:(AbstractArray{T,1} where T), ::AbstractArray{T,1}) where T<:Real at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\adjtrans.jl:284
  ...

In [93]:
x .* y

3-element Array{Int64,1}:
   10
  200
 3000

In [96]:
sum(x .* y) # producto interno

3210

In [97]:
f(x) = x^2 + 1

f (generic function with 1 method)

In [98]:
x

3-element Array{Int64,1}:
 1
 2
 3

In [99]:
f(3)

10

In [100]:
f(x) # error

LoadError: MethodError: no method matching ^(::Array{Int64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Float16, ::Integer) at math.jl:915
  ^(!Matched::Float64, ::Integer) at math.jl:899
  ^(!Matched::BigFloat, ::Integer) at mpfr.jl:599
  ...

In [101]:
f.(x)

3-element Array{Int64,1}:
  2
  5
 10

In [103]:
+(2, 3)

5

## 3.3 Comparaciones numéricas

Igualdad: `==`

In [104]:
3 == 3

true

In [105]:
3 == 4

false

No igual: `!=` o bien $\not =$ mediante `\ne` + tecla `tab`

In [106]:
3 != 4, 3 ≠ 4 

(true, true)

In [107]:
3 ≠ 3

false

Relaciones de orden:

$\leq$ mediante `\le` o bien `<=` 

$\geq$ mediante `\ge` o bien `>=`

In [108]:
4 < 4, 4 ≤ 4, 4 ≥ 4, 4 > 4 

(false, true, true, false)

In [111]:
x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [112]:
2 .≤ x

3-element BitArray{1}:
 0
 1
 1

In [113]:
-Inf < Inf

true

In [114]:
isfinite(3), isfinite(-Inf)

(true, false)

In [115]:
isinf(3), isinf(Inf)

(false, true)

In [116]:
0/0, isnan(0/0)

(NaN, true)

In [117]:
iseven(3), isodd(3)

(false, true)

Comparaciones encadenadas:

In [118]:
1 < 2 ≤ 3 > 2.5

true

In [119]:
1 < 3.1 ≤ 3 > 2.5

false

In [120]:
x = [1, 2, 3, 4, 5]
2 .< x .≤ 5

5-element BitArray{1}:
 0
 0
 1
 1
 1

## 3.4 Redondeo

In [123]:
x = 2.5
y = 3.5;

In [124]:
round(x), round(y)

(2.0, 4.0)

En lo anterior, para el caso particular de `.5` se aplica la regla usual de redondeo hacia abajo/arriba dependiendo de si el dígito a la izquierda es par/impar. En cualquier otro caso, el redondeo es el usual:

In [125]:
round(2.5000001), round(2.4999999)

(3.0, 2.0)

In [126]:
round.([-x, -y])

2-element Array{Float64,1}:
 -2.0
 -4.0

In [127]:
π

π = 3.1415926535897...

In [128]:
round(π, digits = 3), round(π, digits = 7)

(3.142, 3.1415927)

In [129]:
floor(π), ceil(π)

(3.0, 4.0)

In [130]:
trunc(1.99999999999999)

1.0

## 3.5 Algunas otras funciones incluidas

`fld`  `cld`  `mod`  `mod2pi`  `fldmod`  `gcd`  `lcd`

`abs`  `abs2`  `sign`  `copysign`  `flipsign`

`sqrt` √ `cbrt` ∛ `hypot`  `exp`  `log`

`sin` `cos` `tan` `sinh` `atan` `sinpi`  `cospi`  `sind` etc.

Recuerda que puedes averiguar qué hace cada función mediante `?` + nombre de la función. Por ejemplo:

In [131]:
?fld

search: fld fld1 fldmod fldmod1 foldr foldl mapfoldr mapfoldl fieldtype



```
fld(x, y)
```

Largest integer less than or equal to `x/y`. Equivalent to `div(x, y, RoundDown)`.

See also: [`div`](@ref)

# Examples

```jldoctest
julia> fld(7.3,5.5)
1.0
```


## 3.6 Conjuntos

In [133]:
A = [1, 2, 3, 4]
B = [3, 4, 5, 6];

intersección: `\cap` $\cap$       

unión: `\cup` $\cup$

In [134]:
A ∩ B, A ∪ B

([3, 4], [1, 2, 3, 4, 5, 6])

In [135]:
intersect(A, B), union(A, B)

([3, 4], [1, 2, 3, 4, 5, 6])

In [136]:
C = [100, 1000]

2-element Array{Int64,1}:
  100
 1000

In [137]:
A ∩ B ∩ C, A ∪ B ∪ C

(Int64[], [1, 2, 3, 4, 5, 6, 100, 1000])

In [138]:
length(A ∩ B ∩ C)

0

In [139]:
length(A ∪ B)

6

In [140]:
A, B, C

([1, 2, 3, 4], [3, 4, 5, 6], [100, 1000])

In [141]:
A ∩ B ∪ C

4-element Array{Int64,1}:
    3
    4
  100
 1000

In [142]:
(A ∩ B) ∪ C

4-element Array{Int64,1}:
    3
    4
  100
 1000

In [143]:
A ∩ (B ∪ C)

2-element Array{Int64,1}:
 3
 4

In [144]:
A, B

([1, 2, 3, 4], [3, 4, 5, 6])

In [145]:
setdiff(A, B), setdiff(B, A)

([1, 2], [5, 6])

In [146]:
AB = symdiff(A, B)
BA = symdiff(B, A)
AB, BA 

([1, 2, 5, 6], [5, 6, 1, 2])

In [147]:
AB == BA, issetequal(AB, BA)

(false, true)

Pertenencia: `\in` $\in$

No pertenece: `\notin` $\not\in$

In [148]:
2 ∈ AB, 3 ∈ AB

(true, false)

In [149]:
2 ∉ AB, 3 ∉ AB

(false, true)

Subconjunto: `issubset`

In [150]:
issubset([1, 2, 3], [3, 1, 2])

true

In [151]:
issubset([1, 2], [2, 3, 4])

false

O mediante `\subseteq` $\subseteq$

In [152]:
A = [1, 2, 3]
B = [3, 4, 5]
C = A ∪ B
D = A ∩ B
C, D

([1, 2, 3, 4, 5], [3])

In [153]:
A ⊆ B, A ∩ B ⊆ B

(false, true)

In [154]:
A ∩ B ⊆ A ⊆ A ∪ B

true

In [155]:
A ∩ B ⊆ A ⊆ D

false