# 4. Funciones y control de flujo
> Por Arturo Erdely

## 4.1 Definir una función

### En una sola línea de código

In [217]:
α(x) = 2x + 1

α (generic function with 1 method)

In [218]:
α(3) # resultado: entero

7

In [219]:
α(3.0) # resultado: float

7.0

In [220]:
α(3 + 2im) # resultado: complejo

7 + 4im

In [221]:
α(2//7) # resultado: racional

11//7

En lugar de exhibir el resultado de una función, podemos asignarlo directamente a alguna variable, por ejemplo:

In [222]:
r = α(2//7);

In [223]:
r + 1

18//7

Utilizar una función para evaluar cada uno de los elementos de un vector, agregando un punto a lado de la función:

In [224]:
α.([1, 2, 3]) # resultado: vector (columna)

3-element Array{Int64,1}:
 3
 5
 7

Otro ejemplo:

In [225]:
β(x, y, z) = x*y + z

β (generic function with 1 method)

In [226]:
β(2, 3, 4)

10

In [227]:
β(im, -im, im)

1 + 1im

Otro ejemplo:

In [228]:
γ(x, y) = (x*y, x+y, x-y)

γ (generic function with 1 method)

In [229]:
γ(2, 3)

(6, 5, -1)

In [230]:
γ(2//7, 3//5)

(6//35, 31//35, -11//35)

### En varias líneas de código

In [231]:
function δ(x, y, z)
    a = x + y
    b = y*z
    c = a + b*im
end

δ (generic function with 1 method)

In [232]:
δ(1, 2, 3)

3 + 6im

### Con argumentos por defecto

In [233]:
ζ(x, y = 1, z = 2) = x + y*z

ζ (generic function with 3 methods)

In [234]:
ζ(2)

4

In [235]:
ζ(2, 3)

8

In [236]:
ζ(2, 3, 100)

302

### Con argumentos etiquetados

In [ ]:
η(w, x; y = 1, z = 2) = w*z - x*y

In [237]:
η(2, 3)

1

In [238]:
η(2, 3, z = 100)

197

## 4.2 Composición de funciones

In [239]:
θ(x) = (-x, x)

θ (generic function with 1 method)

Operador composición de funciones: `\circ` ∘

In [240]:
raíces = θ ∘ sqrt ∘ abs

#62 (generic function with 1 method)

In [241]:
raíces(25)

(-5.0, 5.0)

Función cuyos argumentos son funciones y su resultado es una función también:

In [242]:
μ(x) = x^2 + 1
ξ(y) = 2y

ξ (generic function with 1 method)

In [243]:
componer(f, g) = f ∘ g

componer (generic function with 1 method)

In [244]:
τ = componer(μ, ξ)

#62 (generic function with 1 method)

In [245]:
τ(3)

37

In [246]:
ϕ = componer(ξ, μ)

#62 (generic function with 1 method)

In [247]:
ϕ(3)

20

## 4.3 Definir nuevos operadores binarios

Si $A$ es un conjunto, un **operador binario cerrado** en $A$ es una función $\oplus:A\times A\rightarrow A$ y denotamos la estructura algebraica $(A,\oplus).$ En `Julia`, como en cualquier otro lenguaje de programación, se tienen predefinidos diversos operadores binarios sobre los distintos conjuntos (tipos) de números que se contemplen. Por ejemplo $(\mathbb{Z},+)$ el conjunto de los números enteros $\mathbb{Z}$ en la forma usual de definir suma $+$ de los mismos:

In [248]:
+(2, 3)

5

Que también es escribe y ejecuta mediante:

In [249]:
2 + 3

5

De hecho por medio de la solicitud de ayuda `?` podemos analizar cómo está definido el operador `+` en `Julia`:

In [250]:
?+

search: +



```
+(x, y...)
```

Addition operator. `x+y+z+...` calls this function with all arguments, i.e. `+(x, y, z, ...)`.

# Examples

```jldoctest
julia> 1 + 20 + 4
25

julia> +(1, 20, 4)
25
```

---

```
dt::Date + t::Time -> DateTime
```

The addition of a `Date` with a `Time` produces a `DateTime`. The hour, minute, second, and millisecond parts of the `Time` are used along with the year, month, and day of the `Date` to create the new `DateTime`. Non-zero microseconds or nanoseconds in the `Time` type will result in an `InexactError` being thrown.


Además de los operadores binarios predefinidos en `Julia` podemos definir nuevos, utilizando símbolos del siguiente catálogo:

Con la misma *precedencia* que la suma usual `+`:

`⊕ ⊖ ⊞ ⊟ ∪ ∨ ⊔ ± ∓ ∔ ∸ ≏ ⊎ ⊻ ⊽ ⋎ ⋓ ⧺ ⧻ ⨈ ⨢ ⨣ ⨤ ⨥ ⨦ ⨧ ⨨ ⨩ ⨪ ⨫ ⨬ ⨭ ⨮ ⨹ ⨺ ⩁ ⩂ ⩅ ⩊ ⩌ ⩏ ⩐ ⩒ ⩔ ⩖ ⩗ ⩛ ⩝ ⩡ ⩢ ⩣`

Con la misma *precedencia* que la multiplicación usual `*`:

`% × ∩ ∧ ⊗ ⊘ ⊙ ⊚ ⊛ ⊠ ⊡ ⊓ ∗ ∙ ∤ ⅋ ≀ ⊼ ⋄ ⋆ ⋇ ⋉ ⋊ ⋋ ⋌ ⋏ ⋒ ⟑ ⦸ ⦼ ⦾ ⦿ ⧶ ⧷ ⨇ ⨰ ⨱ ⨲ ⨳ ⨴ ⨵ ⨶ ⨷ ⨸ ⨻ ⨼ ⨽ ⩀ ⩃ ⩄ ⩋ ⩍ ⩎ ⩑ ⩓ ⩕ ⩘ ⩚ ⩜ ⩞ ⩟ ⩠ ⫛ ⊍ ▷ ⨝ ⟕ ⟖ ⟗`

Por ejemplo, supongamos que queremos definir el operador binario `⊕` de forma que:

x ⊕ y = x + y + 100

In [252]:
⊕(x, y) = x + y + 100 

⊕ (generic function with 1 method)

In [253]:
⊕(1, 2)

103

In [254]:
1 ⊕ 2

103

In [255]:
⊗(x, y) = x*y - 10

⊗ (generic function with 1 method)

In [256]:
2 ⊗ 3

-4

Para ilustrar la *precedencia* de operadores:

In [257]:
4 + 7 * 9, (4 + 7)*9, 4 + (7 * 9)

(67, 99, 67)

In [258]:
4 ⊕ 7 ⊗ 9

157

In [259]:
(4 ⊕ 7) ⊗ 9, 4 ⊕ (7 ⊗ 9)

(989, 157)

quedando clara la precedencia del operador `⊗` sobre `⊕` si no se aclara mediante paréntesis.

## 4.4 Tuplas

Matemáticamente son $n$-adas (ordenadas) que una vez definidas no pueden modificarse parcialmente:

In [260]:
x = (3, 9.1, 5//9, 3 - 2im)

(3, 9.1, 5//9, 3 - 2im)

In [261]:
typeof(x)

Tuple{Int64,Float64,Rational{Int64},Complex{Int64}}

Recuperar alguna de las entradas:

In [262]:
x[3]

5//9

Obtener una subtupla (de dimensión $\geq 2$) con algunas de sus entradas:

In [263]:
x[[2, 4]]

(9.1, 3 - 2im)

In [264]:
x[1:3]

(3, 9.1, 5//9)

No es posible modificar solo algunas de las entradas de una tupla:

In [265]:
x[1] = 4 # error

LoadError: MethodError: no method matching setindex!(::Tuple{Int64,Float64,Rational{Int64},Complex{Int64}}, ::Int64, ::Int64)

In [266]:
x

(3, 9.1, 5//9, 3 - 2im)

Son especialmente útiles para empaquetar en un solo objeto varios resultados. También es posible mediante arreglos y en particular vectores, pero eso lo veremos en otro notebook. Como ejemplo, definamos ahora un operador binario para pares ordenados:

In [267]:
⊠((a, b), (c, d)) = (a*c - b*d, a*d + b*c)

⊠ (generic function with 1 method)

In [268]:
(2, 3) ⊠ (4, 5)

(-7, 22)

Que de hecho es justamente la forma equivalente de definir la multiplicación de números complejos:

In [269]:
(2 + 3im) * (4 + 5im)

-7 + 22im

Con un fin puramente ilustrativo, podemos definir una función que aproveche nuestro recién definido operador binario `⊠` y que convierta el par ordenado resultante en el número complejo que representa:

In [272]:
function complejo((a, b), (c, d))
    parOrdenado = (a, b) ⊠ (c, d)
    parteReal = parOrdenado[1]
    parteImaginaria = parOrdenado[2]
    númeroComplejo = parteReal + parteImaginaria*im
    return númeroComplejo
end

complejo (generic function with 1 method)

In [273]:
complejo((2, 3), (4, 5))

-7 + 22im

En la definición de la función `complejo` no era estrictamente necesario utilizar `return` ya que de omitirsela función simplemente entrega el resultado de la última operación realizada dentro de ella, pero en ocasiones el uso de `return` da mayor claridad al código de programación.

Comparaciones múltiples:

In [274]:
(2, 3, 9) < (1, 5, 8) # evaluar si todas las comparaciones cumplen la condición

false

In [275]:
(2, 3, 9) .< (1, 5, 8) # evaluar las comparaciones de cada componente

(false, true, false)

In [276]:
(1, 2, 3) < (4, 5, 6)

true

In [277]:
(1, 2, 3) .< (4, 5, 6)

(true, true, true)

## 4.5 Evaluación condicional

Uso de `if` `elseif` y `else`

In [278]:
function compara(x, y)
    if x < y
        println("$x es menor que $y")
        resultado = -1
    elseif x > y
        println("$x es mayor que $y")
        resultado = 1
    else
        println("$x es igual a $y")
        resultado = 0
    end
    return resultado
end

compara (generic function with 1 method)

In [279]:
z = compara(-3, -Inf)

-3 es mayor que -Inf


1

In [280]:
z

1

En una evaluación condicional podría usarse únicamente `if`, o bien `if` + `else` también.

In [281]:
compara(3, 99), compara(Inf, Inf)

3 es menor que 99
Inf es igual a Inf


(-1, 0)

Nótese que se creó una tupla, de hecho podríamos asignarla a una variable:

In [282]:
t = (compara(3, 99), compara(Inf, Inf));

3 es menor que 99
Inf es igual a Inf


In [283]:
t

(-1, 0)

## 4.6 Operadores lógicos

Una proposición lógica se evalúa como `true` o `false`, por ejemplo, la evaluación de las siguientes tres proposiciones:

In [284]:
5 ≤ 4, float(π) < big(π) < π, 0 > -Inf

(false, true, true)

In [285]:
typeof(true), typeof(false) # valores tipo Booleano

(Bool, Bool)

Operador **negación** `!`

In [286]:
P = true
!P

false

In [287]:
!!P

true

In [288]:
!(3 < 4)

false

Operadores de **conjunción** `&` versus `&&`

In [289]:
function v(x)
    println(x)
    return true
end
function f(x)
    println(x)
    return false
end

f (generic function with 1 method)

In [290]:
v(1) & v(2)

1
2


true

In [291]:
v(1) && v(2)

1
2


true

In [292]:
v(1) & f(2)

1
2


false

In [293]:
v(1) && f(2)

1
2


false

Hasta el momento se ha obtenido el mismo resultado con `&` que con `&&` pero ahora:

In [294]:
f(1) & v(2)

1
2


false

In [295]:
f(1) && v(2)

1


false

El operador binario `&` evalua ambas proposiciones, pero `&&` en cuanto notó que la primera de las proposiciones era falsa, ya ni se tomó la molestia de evaluar la segunda porque de todos modos el resultado iba a ser falso. 

In [296]:
f(1) & f(2)

1
2


false

In [297]:
f(1) && f(2)

1


false

Operadores de **disyunción** `|` versus `||`

In [298]:
v(1) | v(2)

1
2


true

In [299]:
v(1) || v(2)

1


true

In [300]:
v(1) | f(2)

1
2


true

In [301]:
v(1) || f(2)

1

true

In [302]:
f(1) | v(2)

1
2


true

In [303]:
f(1) || v(2)

1
2


true

In [304]:
f(1) | f(2)

1
2


false

In [305]:
f(1) || f(2)

1
2


false

Ejemplo:

In [306]:
P = (true, true, false, false)
Q = (true, false, true, false);

In [310]:
P .& Q

(true, false, false, false)

In [311]:
P .| Q

(true, true, true, false)

Leyes de Morgan:

In [312]:
.!(P .| Q) .== .!P .& .!Q

(true, true, true, true)

In [313]:
.!(P .& Q) .== .!P .| .!Q

(true, true, true, true)

## 4.7 Ciclos

`for` `while` `continue` `break`

In [314]:
1:10 # indicar un rango de números

1:10

In [315]:
collect(1:10) # convertir un rango de números a números

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [316]:
collect(0:0.1:1)

11-element Array{Float64,1}:
 0.0
 0.1
 0.2
 0.3
 0.4
 0.5
 0.6
 0.7
 0.8
 0.9
 1.0

### Ciclo `for`

Mediante `\in` + la tecla `tab` se obtiene ∈

In [317]:
for i ∈ 1:10 # también puede escribirse: for i in 1:10
    print(i^2, " ")
end

1 4 9 16 25 36 49 64 81 100 

In [318]:
function suma2(conjunto)
    suma = 0
    for n ∈ conjunto
        c = n^2
        print(c, " ")
        suma = suma + c
    end
    return suma
end

suma2 (generic function with 1 method)

In [319]:
suma2(1:10)

1 4 9 16 25 36 49 64 81 100 

385

In [320]:
suma2((-80, 1, 5, 11))

6400 1 25 121 

6547

In [321]:
suma2((-Inf, 5, Inf))

Inf 25 Inf 

Inf

### Ciclo `while` 

In [322]:
function fibonacci(máximo)
    ant = 0
    sig = 1
    print(ant, " ", sig)
    while sig ≤ máximo
        fib = ant + sig
        ant = sig
        sig = fib
        print(" ", fib)
    end
    return nothing # o bien podría omitirse
end     

fibonacci (generic function with 1 method)

In [323]:
fibonacci(150)

0 1 1 2 3 5 8 13 21 34 55 89 144 233

In [324]:
fibonacci(0)

0 1

### Uso de `continue` y `break`

In [325]:
function sumaNo7(n)
    suma = 0
    for i ∈ 1:n
        if i ≠ 7 # \ne + tab --> ≠ o bien utilizar !=
            print(i, " ")
            suma = suma + i
        else
            continue
        end
    end
    return suma
end

sumaNo7 (generic function with 1 method)

In [326]:
sumaNo7(10)

1 2 3 4 5 6 8 9 10 

48

In [ ]:
function sumaNo7bye23(n)
    suma = 0
    for i ∈ 1:n
        if i == 7
            continue
        elseif i == 23
            break
        else
            print(i, " ")
            suma = suma + i
        end
    end
    return suma
end

In [327]:
sumaNo7bye23(10)

1 2 3 4 5 6 8 9 10 

48

In [328]:
sumaNo7bye23(25)

1 2 3 4 5 6 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 

246