# 5. Arreglos multidimensionales
> Por Arturo Erdely

Recordemos algunos los numéricos analizados hasta el momento:

In [1]:
typeof.((true, 1, 1.0, 1//1, 1 + 1im, 1.0 + 1.0im, 1//1 + 1//1*im))

(Bool, Int64, Float64, Rational{Int64}, Complex{Int64}, Complex{Float64}, Complex{Rational{Int64}})

Crear un arreglo de ceros tipo *entero* con dimensiones $2\times 3$:

In [2]:
A = zeros(Int64, 2, 3)

2×3 Array{Int64,2}:
 0  0  0
 0  0  0

De hecho bastaría con escribir `Int` y automáticamente se asignará el tipo `Int64` si se trata de una computadora a 64 bits, o bien el tipo `Int32` si es a 32 bits:

In [3]:
A = zeros(Int, 2, 3)

2×3 Array{Int64,2}:
 0  0  0
 0  0  0

Ahora un arreglo de unos tipo *racional* con dimensiones $3\times 2$:

In [4]:
B = ones(Rational{Int64}, 3, 2)

3×2 Array{Rational{Int64},2}:
 1//1  1//1
 1//1  1//1
 1//1  1//1

Un arreglo de tipo *Booleano* con puros falsos, dimensiones $1\times 3$:

In [5]:
C = falses(1, 3)

1×3 BitArray{2}:
 0  0  0

Booleano pero con verdaderos, dimensiones $3\times 1$:

In [6]:
D = trues(3, 1)

3×1 BitArray{2}:
 1
 1
 1

Arreglo de ceros de tipo *punto flotante* de dimensiones $2\times 3\times 4$:

In [7]:
E = zeros(Float64, 2, 3, 4)

2×3×4 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0
 0.0  0.0  0.0

De hecho, si no se especifica el tipo numérico, por defecto es de punto flotante:

In [8]:
E = zeros(2, 3, 4)

2×3×4 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0
 0.0  0.0  0.0

Una vez creado un arreglo, basta con especificar cada entrada mediante sus coordenadas entre corteches y separando por comas:

In [9]:
G = zeros(3,4)

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [10]:
G[2, 3] = π

π = 3.1415926535897...

In [11]:
G

3×4 Array{Float64,2}:
 0.0  0.0  0.0      0.0
 0.0  0.0  3.14159  0.0
 0.0  0.0  0.0      0.0

In [12]:
G[2, 3]

3.141592653589793

Modificar una fila completa:

In [13]:
G[1, :] = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [14]:
G

3×4 Array{Float64,2}:
 1.0  2.0  3.0      4.0
 0.0  0.0  3.14159  0.0
 0.0  0.0  0.0      0.0

Modificar una columna:

In [15]:
G[: , 2] = ℯ # error porque falta un punto antes del símbolo `=` para vectorizar la asignación

LoadError: ArgumentError: indexed assignment with a single value to many locations is not supported; perhaps use broadcasting `.=` instead?

In [16]:
G[: , 2] .= ℯ 

3-element view(::Array{Float64,2}, :, 2) with eltype Float64:
 2.718281828459045
 2.718281828459045
 2.718281828459045

In [17]:
G

3×4 Array{Float64,2}:
 1.0  2.71828  3.0      4.0
 0.0  2.71828  3.14159  0.0
 0.0  2.71828  0.0      0.0

Obtener submatrices:

In [18]:
G[2:3, 3:4]

2×2 Array{Float64,2}:
 3.14159  0.0
 0.0      0.0

In [19]:
G[[1, 3], [2, 4]]

2×2 Array{Float64,2}:
 2.71828  4.0
 2.71828  0.0

Nótese que así puede defirse un arreglo de $3\times 1$:

In [20]:
[1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

Y así uno de $1\times 3$:

In [21]:
[1 2 3]

1×3 Array{Int64,2}:
 1  2  3

O así uno de $2\times 3$:

In [22]:
[1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

También es posible crear arreglos de esta forma:

In [23]:
H = fill(9, 3, 5)

3×5 Array{Int64,2}:
 9  9  9  9  9
 9  9  9  9  9
 9  9  9  9  9

También es posible crear **arreglos de funciones**, por ejemplo:

In [24]:
f(x) = 2x + 1
g(x) = x^2
h(x) = x^3 

h (generic function with 1 method)

In [25]:
I = [f, g, h]

3-element Array{Function,1}:
 f (generic function with 1 method)
 g (generic function with 1 method)
 h (generic function with 1 method)

In [26]:
I[2, 1](5)

25

En este aso, por ser una matriz de una sola columna, se le considera vector columna y no es necesario especificar la
columna 1:

In [27]:
I[1](100)

201

Crearemos un arreglo `J` de funciones, como composición de pares de funciones del vector de funciones `I`:

In [28]:
J = Array{Function, 2}(undef, 3, 3)

3×3 Array{Function,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef
 #undef  #undef  #undef

In [29]:
for i ∈ 1:3
    for j ∈ 1:3
        J[i, j] = I[i] ∘ I[j]
    end
end
J

3×3 Array{Function,2}:
 #62  #62  #62
 #62  #62  #62
 #62  #62  #62

In [30]:
J[2, 3]

#62 (generic function with 1 method)

In [31]:
J[1, 2](10), (f ∘ g)(10)

(201, 201)

## 5.1 Transformaciones

In [32]:
K = zeros(3, 4)

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [33]:
L = K # L se convierte en un espejo de K, y viceversa
M = copy(K) # M es una copia independiente de K

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [34]:
K

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [35]:
L

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [36]:
M

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [37]:
K[2, 1] = π
K

3×4 Array{Float64,2}:
 0.0      0.0  0.0  0.0
 3.14159  0.0  0.0  0.0
 0.0      0.0  0.0  0.0

In [38]:
L

3×4 Array{Float64,2}:
 0.0      0.0  0.0  0.0
 3.14159  0.0  0.0  0.0
 0.0      0.0  0.0  0.0

In [39]:
M

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [40]:
L[3, 4] = ℯ
L

3×4 Array{Float64,2}:
 0.0      0.0  0.0  0.0
 3.14159  0.0  0.0  0.0
 0.0      0.0  0.0  2.71828

In [41]:
K

3×4 Array{Float64,2}:
 0.0      0.0  0.0  0.0
 3.14159  0.0  0.0  0.0
 0.0      0.0  0.0  2.71828

In [42]:
tK = transpose(K) # transpuesta

4×3 LinearAlgebra.Transpose{Float64,Array{Float64,2}}:
 0.0  3.14159  0.0
 0.0  0.0      0.0
 0.0  0.0      0.0
 0.0  0.0      2.71828

In [43]:
rK = reshape(K, 6, 2)
vK = vec(rK);

In [44]:
K

3×4 Array{Float64,2}:
 0.0      0.0  0.0  0.0
 3.14159  0.0  0.0  0.0
 0.0      0.0  0.0  2.71828

In [45]:
rK

6×2 Array{Float64,2}:
 0.0      0.0
 3.14159  0.0
 0.0      0.0
 0.0      0.0
 0.0      0.0
 0.0      2.71828

In [46]:
vK

12-element Array{Float64,1}:
 0.0
 3.141592653589793
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 2.718281828459045

Rellenar mediante una sucesión:

In [47]:
1:12

1:12

In [48]:
collect(1:12)

12-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12

In [49]:
N = reshape(collect(1:12), 3, 4)

3×4 Array{Int64,2}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [50]:
P = transpose(reshape(collect(1:12), 4, 3))

3×4 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

Obtener información sobre un arreglo:

In [51]:
ndims(P)

2

In [52]:
size(P)

(3, 4)

In [53]:
typeof(P)

LinearAlgebra.Transpose{Int64,Array{Int64,2}}

In [54]:
eltype(P)

Int64

## 5.2 Operaciones

Aplicar una función a todas los elementos de un arreglo:

In [55]:
ℓ(x) = x^2 + 1

ℓ (generic function with 1 method)

In [56]:
ℓ.(P)

3×4 Array{Int64,2}:
  2    5   10   17
 26   37   50   65
 82  101  122  145

In [57]:
P

3×4 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [58]:
P + 1 # error, porque falta vectorizar la operación

LoadError: MethodError: no method matching +(::LinearAlgebra.Transpose{Int64,Array{Int64,2}}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(!Matched::Missing, ::Number) at missing.jl:115
  +(!Matched::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:116
  ...

In [59]:
P .+ 1

3×4 Array{Int64,2}:
  2   3   4   5
  6   7   8   9
 10  11  12  13

In [60]:
(P .+ 1) .≤ 8

3×4 BitArray{2}:
 1  1  1  1
 1  1  1  0
 0  0  0  0

In [61]:
P

3×4 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
 1   2   3   4
 5   6   7   8
 9  10  11  12

In [62]:
Q = 100 .* P

3×4 Array{Int64,2}:
 100   200   300   400
 500   600   700   800
 900  1000  1100  1200

In [63]:
P + Q

3×4 Array{Int64,2}:
 101   202   303   404
 505   606   707   808
 909  1010  1111  1212

In [64]:
P .* Q # multiplicación P[i, j]*Q[i,j]

3×4 Array{Int64,2}:
  100    400    900   1600
 2500   3600   4900   6400
 8100  10000  12100  14400

In [65]:
R = reshape(collect(1:9), 3, 3)

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [66]:
S = 100 .* R

3×3 Array{Int64,2}:
 100  400  700
 200  500  800
 300  600  900

In [67]:
R .* S # multiplicación P[i, j]*Q[i,j]

3×3 Array{Int64,2}:
 100  1600  4900
 400  2500  6400
 900  3600  8100

In [68]:
R * S # multiplicación de matrices

3×3 Array{Int64,2}:
 3000  6600  10200
 3600  8100  12600
 4200  9600  15000

In [69]:
T = rand(3, 3) # rellenar con números pseudoaleatorios con distribución Uniforme(0,1)

3×3 Array{Float64,2}:
 0.362177  0.714432  0.558907
 0.57613   0.64894   0.204508
 0.29038   0.866241  0.0330241

In [70]:
invT = inv(T)

3×3 Array{Float64,2}:
 -1.06625    3.15348   -1.48302
  0.276342  -1.02936    1.69764
  2.12691   -0.727689  -1.20902

In [71]:
round.(T * invT, digits = 4)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

Más sobre *Álgebra Lineal* en `Julia`: https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/ 